language: java
sudo: false # faster builds
cache:
  directories:
  - $HOME/.m2

before_install:
  # ignore travis settings.xml
  - rm -f $HOME/.m2/settings.xml
#   # uncomment below when investigating
#   # maven behaviour
#   - mvn help:effective-pom
#   - mvn help:effective-settings

# otherwise there is a
# [ERROR] java.nio.file.NoSuchFileException: /home/travis/build/AmadeusITGroup/unbreakable-branches-jenkins/target/classes/META-INF/annotations/hudson.Extension
jdk:
  - openjdk8

# code coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
